# Generated by Django 4.0.4 on 2022-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('inSentence', models.TextField()),
            ],
        ),
    ]
